"""
Django settings for core project.
Generated by 'django-admin startproject' using Django 4.2.27.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# دایرکتوری اصلی پروژه (جایی که manage.py قرار دارد)
BASE_DIR = Path(__file__).resolve().parent.parent
DB_DIR = os.path.join(BASE_DIR, 'db_volume')
if not os.path.exists(DB_DIR):
    os.makedirs(DB_DIR)

# لود کردن متغیرهای محیطی از فایل .env بدون نیاز به پرینت‌های اضافی
ENV_PATH = BASE_DIR / '.env'
if ENV_PATH.exists():
    load_dotenv(dotenv_path=str(ENV_PATH))

# امنیت پروژه
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "django-insecure-_z*oav5vu)2qx$n^)x!_muuujxh+1h1wx2r_)_-dh4u$&hn^4%")
DEBUG = True
ALLOWED_HOSTS = ["*"] # تنظیم برای دسترسی راحت‌تر روی داکر و لوکال


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "documents",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(DB_DIR, 'db.sqlite3'), 
    }
}

# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization

LANGUAGE_CODE = "fa-ir" # تغییر به فارسی برای راست‌چین شدن و شکیل شدن پنل ادمین
TIME_ZONE = "Asia/Tehran"
USE_I18N = True
USE_TZ = True


# Static and Media files (تنظیمات حیاتی برای آپلود اسناد شما)

STATIC_URL = "static/"

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# متغیر اختصاصی برای اتصال به هوش مصنوعی با متد خواندن استاندارد
OPENROUTER_API_KEY = os.environ.get("OPENROUTER_API_KEY")