# Generated by Django 4.2.30 on 2026-05-28 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="عنوان سند")),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/", verbose_name="فایل سند (docx)"
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, null=True, verbose_name="متن استخراج شده"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاریخ بروزرسانی"),
                ),
            ],
            options={
                "verbose_name": "سند",
                "verbose_name_plural": "اسناد",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="پرسش کاربر")),
                ("answer", models.TextField(verbose_name="پاسخ مدل زبانی")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت"),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chats",
                        to="documents.document",
                        verbose_name="سند مربوطه",
                    ),
                ),
            ],
            options={
                "verbose_name": "تاریخچه گفتگو",
                "verbose_name_plural": "تاریخچه گفتگوها",
                "ordering": ["-created_at"],
            },
        ),
    ]
