# Generated by Django 4.2.30 on 2026-05-30 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalSearch",
            fields=[],
            options={
                "verbose_name": "جست\u200cجوی سراسری میان تمام اسناد",
                "verbose_name_plural": "🔎 جست\u200cجوی سراسری میان تمام اسناد",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("documents.document",),
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="متن پرسش شما")),
                (
                    "answer",
                    models.TextField(
                        blank=True, null=True, verbose_name="پاسخ هوش مصنوعی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان پرسش"),
                ),
                (
                    "target_document",
                    models.ForeignKey(
                        blank=True,
                        help_text="اگر سندی را انتخاب نکنید، جست\u200cجو به صورت خودکار میان تمام اسناد انجام می\u200cشود.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="documents.document",
                        verbose_name="محدوده جست\u200cجو",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرسش از اسناد",
                "verbose_name_plural": "💬 اتاق پرسش و پاسخ هوش مصنوعی",
                "ordering": ["-created_at"],
            },
        ),
    ]
