# Generated by Django 4.2.30 on 2026-05-30 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0002_globalsearch_chatsession"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatsession",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "پرسش از اسناد",
                "verbose_name_plural": "پرسش از اسناد",
            },
        ),
    ]
