# Generated by Django 4.2.30 on 2026-05-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0003_alter_chatsession_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chathistory",
            name="document",
        ),
        migrations.DeleteModel(
            name="GlobalSearch",
        ),
        migrations.AlterModelOptions(
            name="chatsession",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "پرسش و پاسخ",
                "verbose_name_plural": "💬 اتاق پرسش و تاریخچه گفتگوها",
            },
        ),
        migrations.AlterModelOptions(
            name="document",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "سند",
                "verbose_name_plural": "📚 مدیریت و آپلود اسناد",
            },
        ),
        migrations.AddField(
            model_name="chatsession",
            name="tags",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="برچسب\u200cهای هوشمند (Tags)",
            ),
        ),
        migrations.DeleteModel(
            name="ChatHistory",
        ),
    ]
