# Generated by Django 4.2.30 on 2026-05-30 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0004_remove_chathistory_document_delete_globalsearch_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="نام برچسب"
                    ),
                ),
            ],
            options={
                "verbose_name": "برچسب",
                "verbose_name_plural": "🏷️ مدیریت برچسب\u200cها",
            },
        ),
        migrations.RemoveField(
            model_name="chatsession",
            name="tags",
        ),
        migrations.AddField(
            model_name="chatsession",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="sessions",
                to="documents.tag",
                verbose_name="برچسب\u200cهای هوشمند",
            ),
        ),
    ]
